package com.kaiburr.taskmanager.repository;

import com.kaiburr.taskmanager.model.Task;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TaskRepository extends MongoRepository<Task, String> {

    /**
     * Custom finder method to search for tasks where the name contains
     * the provided string, ignoring case.
     * This query is automatically generated by Spring Data from the method name.
     * [cite: 74]
     */
    List<Task> findByNameContainingIgnoreCase(String name);
}